spring.datasource.url=jdbc:postgresql://localhost:5432/todo
spring.datasource.username=postgres
spring.datasource.password=SicParvisMagna4

spring.cloud.function.definition=newUserActionConsume
spring.cloud.stream.bindings.newUserActionConsume-in-0.destination=planner-dest
spring.cloud.stream.bindings.newUserActionConsume-in-0.group=planner-group
